#!/bin/sh

storage="$HOME/.aim/"

case $1 in

  install)
    curl -o "$storage/repo" https://raw.githubusercontent.com/miguelrcborges/AppImageMan/main/repo
    link=$(grep "$2 " "$storage/repo")
    

    if [ -z "$link" ]; then
      echo Package not found.
      exit
    fi

    cd $storage
    curl -o "$2.AppImage" -L $(echo $link | cut -d " " -f 3) 
    chmod +x "$2.AppImage"
    ./$2.AppImage --appimage-extract
    
    desktop=$(find squashfs-root/*.desktop)
    png=$(find squashfs-root/*.png)
    mv $png $2.png
    sed -i '/Exec=/d' $desktop
    sed -i '/Icon=/d' $desktop
    echo "Exec=$storage$2.AppImage" >> $desktop
    echo "Icon=$storage$2.png" >> $desktop
    mv $desktop $HOME/.local/share/applications/$2-appimage.desktop
    rm -rf squashfs-root

    echo "$2 was installed with success."
    ;;


  remove)
    cd $storage
    if ! test -f "./$2.AppImage"; then
      echo "$2 isn't installed."
      exit
    fi

    rm $2.AppImage $2.png $HOME/.local/share/applications/$2-appimage.desktop

    echo "$2 was uninstalled."
    ;;

  *)
    echo "Usage: (install | remove | update)
      
      - install <package>: Downloads the AppImage and generates the desktop file.
      - remove <package>: Remove the AppImage and it's desktop file.
      - update: Update all installed AppImages.

      "
    ;;
esac
