#!/bin/sh

storage="$HOME/.aim/"

case $1 in

  install)
    curl -o "$storage/repo" https://raw.githubusercontent.com/miguelrcborges/AppImageMan/main/repo
    link=$(grep "$2 " "$storage/repo")
    

    if [ -z "$link" ]; then
      echo Package not found.
      exit
    fi

    echo heyooo
    ;;


  *)
    echo "Usage: (install | remove | update)
      
      - install <package>: Downloads the AppImage and generates the desktop file.
      - remove <package>: Remove the AppImage and it's desktop file.
      - update: Update all installed AppImages.

      "
    ;;
esac
